#ifndef MYFORMULSDLL_GLOBAL_H
#define MYFORMULSDLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MYFORMULSDLL_LIBRARY)
#  define MYFORMULSDLLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MYFORMULSDLLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MYFORMULSDLL_GLOBAL_H
